# -*- coding: utf-8 -*-
"""BooleanMasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGeE-YKb-A3ig6YeI78WD-m3mPRRRJUC

**Maestría en Inteligencia Artificial y Analítica de Datos**

Curso: *Programación para Analítica Descriptiva y Predictiva*

* Semestre: Enero-Junio 2026
* Profesor: Dr. Vicente García Jiménez
* Alumno: Ricardo Solano Monje
* Matrícula: 266221
* Unidad 1
* Práctica 5: Uso de máscaras booleanas
* Objetivo de la práctica: Usar NumPy para crear máscaras booleanas y utilizarlas para seleccionar elementos de un arreglo que cumplan un criterio específico (condición).
* Programa realizado por: Ricardo Solano Monje

## Uso de máscaras booleanas.

* Crea un arreglo unidimensional con 15 números aleatorios entre 1 y 50. Luego:
* Selecciona los elementos mayores que 25 utilizando una máscara booleana.
* Cuenta cuántos elementos son mayores que 25.
"""

# Using boolean masks.
# 1. Create a one-dimensional array with 15 random numbers between 1 and 50
import numpy as np


np.random.seed(42)  # sets a seed to make the random numbers reproducible.
                    #This is optional; if you want different numbers each time, you can remove it.
array = np.random.randint(1, 51, 15)  # creates an array of 15 random integers between 1 and 50 (inclusive)
                                        # 51 is used because `randint` is exclusive on the upper bound.

print("Original array:\n")
print(array)
print()

# 2. Selecting elements greater than 25 using a Boolean mask:
mask = array > 25  # Esto crea un arreglo booleano con True donde se cumple la condición
                        # Creates the Boolean mask with True where the condition is met..
                        #For example, if array = [30, 20, 40], then mask = [True, False, True]
elementsGreater25 = array[mask]  # here applaying the mask

print("Elements greater than 25:\n")
print(elementsGreater25)
print()

# 3. Counting how many elements are greater than 25
count = np.sum(mask)  # sums the True values in the mask, since in Python, True = 1 and False = 0.
                    # it could also be used: len(elementsGreater25)

print(f"There are {count} elements greater than 25")

